/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package divestoclimb.gasmixer;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int about=0x7f020000;
        public static final int blend=0x7f020001;
        public static final int blend_32=0x7f020002;
        public static final int topup_32=0x7f020003;
        public static final int topup_pick=0x7f020004;
        public static final int units_imperial=0x7f020005;
        public static final int units_metric=0x7f020006;
    }
    public static final class id {
        public static final int about=0x7f06003b;
        public static final int about_text=0x7f060000;
        public static final int blend_result=0x7f060001;
        public static final int button_blend=0x7f06001c;
        public static final int button_copy=0x7f060002;
        public static final int button_topup=0x7f06002d;
        public static final int button_topup_set=0x7f060036;
        public static final int desired_he=0x7f06000e;
        public static final int desired_o2=0x7f06000a;
        public static final int desired_pres=0x7f060006;
        public static final int desired_pres_unit=0x7f060004;
        public static final int minus_desired_he=0x7f06000d;
        public static final int minus_desired_o2=0x7f060009;
        public static final int minus_desired_pres=0x7f060005;
        public static final int minus_start_he=0x7f060019;
        public static final int minus_start_o2=0x7f060015;
        public static final int minus_start_pres=0x7f060011;
        public static final int minus_topup_final_pres=0x7f06002a;
        public static final int minus_topup_he=0x7f060033;
        public static final int minus_topup_o2=0x7f06002f;
        public static final int minus_topup_start_he=0x7f060027;
        public static final int minus_topup_start_o2=0x7f060023;
        public static final int minus_topup_start_pres=0x7f06001f;
        public static final int plus_desired_he=0x7f06000f;
        public static final int plus_desired_o2=0x7f06000b;
        public static final int plus_desired_pres=0x7f060007;
        public static final int plus_start_he=0x7f06001b;
        public static final int plus_start_o2=0x7f060017;
        public static final int plus_start_pres=0x7f060013;
        public static final int plus_topup_final_pres=0x7f06002c;
        public static final int plus_topup_he=0x7f060035;
        public static final int plus_topup_o2=0x7f060031;
        public static final int plus_topup_start_he=0x7f060029;
        public static final int plus_topup_start_o2=0x7f060025;
        public static final int plus_topup_start_pres=0x7f060021;
        public static final int set_topup=0x7f060038;
        public static final int slider_desired_he=0x7f06000c;
        public static final int slider_desired_o2=0x7f060008;
        public static final int slider_start_he=0x7f060018;
        public static final int slider_start_o2=0x7f060014;
        public static final int slider_topup_he=0x7f060032;
        public static final int slider_topup_o2=0x7f06002e;
        public static final int slider_topup_start_he=0x7f060026;
        public static final int slider_topup_start_o2=0x7f060022;
        public static final int start_he=0x7f06001a;
        public static final int start_o2=0x7f060016;
        public static final int start_pres=0x7f060012;
        public static final int start_pres_unit=0x7f060010;
        public static final int switch_unit_imperial=0x7f06003a;
        public static final int switch_unit_metric=0x7f060039;
        public static final int tab_blend=0x7f060003;
        public static final int tab_topup=0x7f06001d;
        public static final int topup_final_pres=0x7f06002b;
        public static final int topup_he=0x7f060034;
        public static final int topup_o2=0x7f060030;
        public static final int topup_result=0x7f060037;
        public static final int topup_start_he=0x7f060028;
        public static final int topup_start_o2=0x7f060024;
        public static final int topup_start_pres=0x7f060020;
        public static final int topup_start_pres_unit=0x7f06001e;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int blend_result=0x7f030001;
        public static final int main=0x7f030002;
        public static final int sandbox=0x7f030003;
        public static final int set_topup=0x7f030004;
        public static final int topup_result=0x7f030005;
    }
    public static final class menu {
        public static final int main=0x7f050000;
    }
    public static final class string {
        public static final int about=0x7f04001e;
        public static final int about_text=0x7f040020;
        public static final int air=0x7f040011;
        public static final int app_name=0x7f040000;
        public static final int button_blend=0x7f04000c;
        public static final int button_topup=0x7f04001c;
        public static final int change=0x7f04001f;
        public static final int copy=0x7f04000d;
        public static final int depth_imperial=0x7f040005;
        public static final int depth_metric=0x7f040006;
        public static final int desired=0x7f040009;
        public static final int enough=0x7f04000e;
        public static final int he=0x7f040001;
        public static final int helium=0x7f040010;
        public static final int nitrogen=0x7f040012;
        public static final int o2=0x7f040002;
        public static final int oxygen=0x7f04000f;
        public static final int pres_imperial=0x7f040003;
        public static final int pres_metric=0x7f040004;
        public static final int result_add=0x7f040017;
        public static final int result_drain=0x7f040016;
        public static final int result_end=0x7f040019;
        public static final int result_impossible=0x7f040013;
        public static final int result_start=0x7f040015;
        public static final int result_start_empty=0x7f040014;
        public static final int result_topup=0x7f040018;
        public static final int set_topup=0x7f04001d;
        public static final int starting=0x7f04000a;
        public static final int switch_to_imperial=0x7f040008;
        public static final int switch_to_metric=0x7f040007;
        public static final int topup_mix=0x7f04000b;
        public static final int topup_pres=0x7f04001b;
        public static final int topup_result=0x7f04001a;
    }
}
